/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { DataEmbeddingCreateNestedManyWithoutChatbotsInput } from "./DataEmbeddingCreateNestedManyWithoutChatbotsInput";
import { Type } from "class-transformer";
import { FaqCreateNestedManyWithoutChatbotsInput } from "./FaqCreateNestedManyWithoutChatbotsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class ChatbotCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  botName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  companyName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  contactDetails?: string | null;

  @ApiProperty({
    required: false,
    type: () => DataEmbeddingCreateNestedManyWithoutChatbotsInput,
  })
  @ValidateNested()
  @Type(() => DataEmbeddingCreateNestedManyWithoutChatbotsInput)
  @IsOptional()
  @Field(() => DataEmbeddingCreateNestedManyWithoutChatbotsInput, {
    nullable: true,
  })
  dataEmbeddings?: DataEmbeddingCreateNestedManyWithoutChatbotsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => FaqCreateNestedManyWithoutChatbotsInput,
  })
  @ValidateNested()
  @Type(() => FaqCreateNestedManyWithoutChatbotsInput)
  @IsOptional()
  @Field(() => FaqCreateNestedManyWithoutChatbotsInput, {
    nullable: true,
  })
  faqs?: FaqCreateNestedManyWithoutChatbotsInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { ChatbotCreateInput as ChatbotCreateInput };
