/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ChatbotService } from "../chatbot.service";
import { ChatbotCreateInput } from "./ChatbotCreateInput";
import { Chatbot } from "./Chatbot";
import { ChatbotFindManyArgs } from "./ChatbotFindManyArgs";
import { ChatbotWhereUniqueInput } from "./ChatbotWhereUniqueInput";
import { ChatbotUpdateInput } from "./ChatbotUpdateInput";
import { DataEmbeddingFindManyArgs } from "../../dataEmbedding/base/DataEmbeddingFindManyArgs";
import { DataEmbedding } from "../../dataEmbedding/base/DataEmbedding";
import { DataEmbeddingWhereUniqueInput } from "../../dataEmbedding/base/DataEmbeddingWhereUniqueInput";
import { FaqFindManyArgs } from "../../faq/base/FaqFindManyArgs";
import { Faq } from "../../faq/base/Faq";
import { FaqWhereUniqueInput } from "../../faq/base/FaqWhereUniqueInput";

export class ChatbotControllerBase {
  constructor(protected readonly service: ChatbotService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Chatbot })
  async createChatbot(
    @common.Body() data: ChatbotCreateInput
  ): Promise<Chatbot> {
    return await this.service.createChatbot({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        botName: true,
        companyName: true,
        contactDetails: true,
        createdAt: true,
        description: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Chatbot] })
  @ApiNestedQuery(ChatbotFindManyArgs)
  async chatbots(@common.Req() request: Request): Promise<Chatbot[]> {
    const args = plainToClass(ChatbotFindManyArgs, request.query);
    return this.service.chatbots({
      ...args,
      select: {
        botName: true,
        companyName: true,
        contactDetails: true,
        createdAt: true,
        description: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Chatbot })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async chatbot(
    @common.Param() params: ChatbotWhereUniqueInput
  ): Promise<Chatbot | null> {
    const result = await this.service.chatbot({
      where: params,
      select: {
        botName: true,
        companyName: true,
        contactDetails: true,
        createdAt: true,
        description: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Chatbot })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateChatbot(
    @common.Param() params: ChatbotWhereUniqueInput,
    @common.Body() data: ChatbotUpdateInput
  ): Promise<Chatbot | null> {
    try {
      return await this.service.updateChatbot({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          botName: true,
          companyName: true,
          contactDetails: true,
          createdAt: true,
          description: true,
          id: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Chatbot })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteChatbot(
    @common.Param() params: ChatbotWhereUniqueInput
  ): Promise<Chatbot | null> {
    try {
      return await this.service.deleteChatbot({
        where: params,
        select: {
          botName: true,
          companyName: true,
          contactDetails: true,
          createdAt: true,
          description: true,
          id: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/dataEmbeddings")
  @ApiNestedQuery(DataEmbeddingFindManyArgs)
  async findDataEmbeddings(
    @common.Req() request: Request,
    @common.Param() params: ChatbotWhereUniqueInput
  ): Promise<DataEmbedding[]> {
    const query = plainToClass(DataEmbeddingFindManyArgs, request.query);
    const results = await this.service.findDataEmbeddings(params.id, {
      ...query,
      select: {
        chatbot: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        data: true,
        embedding: true,
        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/dataEmbeddings")
  async connectDataEmbeddings(
    @common.Param() params: ChatbotWhereUniqueInput,
    @common.Body() body: DataEmbeddingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dataEmbeddings: {
        connect: body,
      },
    };
    await this.service.updateChatbot({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/dataEmbeddings")
  async updateDataEmbeddings(
    @common.Param() params: ChatbotWhereUniqueInput,
    @common.Body() body: DataEmbeddingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dataEmbeddings: {
        set: body,
      },
    };
    await this.service.updateChatbot({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/dataEmbeddings")
  async disconnectDataEmbeddings(
    @common.Param() params: ChatbotWhereUniqueInput,
    @common.Body() body: DataEmbeddingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dataEmbeddings: {
        disconnect: body,
      },
    };
    await this.service.updateChatbot({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/faqs")
  @ApiNestedQuery(FaqFindManyArgs)
  async findFaqs(
    @common.Req() request: Request,
    @common.Param() params: ChatbotWhereUniqueInput
  ): Promise<Faq[]> {
    const query = plainToClass(FaqFindManyArgs, request.query);
    const results = await this.service.findFaqs(params.id, {
      ...query,
      select: {
        answer: true,

        chatbot: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        question: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/faqs")
  async connectFaqs(
    @common.Param() params: ChatbotWhereUniqueInput,
    @common.Body() body: FaqWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      faqs: {
        connect: body,
      },
    };
    await this.service.updateChatbot({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/faqs")
  async updateFaqs(
    @common.Param() params: ChatbotWhereUniqueInput,
    @common.Body() body: FaqWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      faqs: {
        set: body,
      },
    };
    await this.service.updateChatbot({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/faqs")
  async disconnectFaqs(
    @common.Param() params: ChatbotWhereUniqueInput,
    @common.Body() body: FaqWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      faqs: {
        disconnect: body,
      },
    };
    await this.service.updateChatbot({
      where: params,
      data,
      select: { id: true },
    });
  }
}
