/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { DataEmbeddingUpdateManyWithoutChatbotsInput } from "./DataEmbeddingUpdateManyWithoutChatbotsInput";
import { Type } from "class-transformer";
import { FaqUpdateManyWithoutChatbotsInput } from "./FaqUpdateManyWithoutChatbotsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class ChatbotUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  botName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  companyName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  contactDetails?: string | null;

  @ApiProperty({
    required: false,
    type: () => DataEmbeddingUpdateManyWithoutChatbotsInput,
  })
  @ValidateNested()
  @Type(() => DataEmbeddingUpdateManyWithoutChatbotsInput)
  @IsOptional()
  @Field(() => DataEmbeddingUpdateManyWithoutChatbotsInput, {
    nullable: true,
  })
  dataEmbeddings?: DataEmbeddingUpdateManyWithoutChatbotsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => FaqUpdateManyWithoutChatbotsInput,
  })
  @ValidateNested()
  @Type(() => FaqUpdateManyWithoutChatbotsInput)
  @IsOptional()
  @Field(() => FaqUpdateManyWithoutChatbotsInput, {
    nullable: true,
  })
  faqs?: FaqUpdateManyWithoutChatbotsInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { ChatbotUpdateInput as ChatbotUpdateInput };
